In [3]:
import polars as pl
import numpy as np
import matplotlib.pyplot as plt
from data.pre_process import parse_hhmmss_seconds, parse_mmss_seconds

## Objectif

Ici nous nous proposons d'explorer la base de données initiale afin d'indentifier 
quelles sont les variables pertinentes à jeter, c'est à dire les variables qui n'ont
aucune valeur dans le sens où elles n'apportent aucune information, ou les variables qui
sont rendondantes, c'est à dire qu'elles affichent exactement la même données qu'une autre 
colonne mais sous une autre forme, par exemple parse qui est l'inverse de la vitesse.

Nous verrons ensuite comment filtrer les lignes, on verra que cela va surtout se 
concentrer sur les données des splits qui sont parfois lacunaire, ou même désordonnées.

Et nous appliquerons ensuit ces modification sur donnees_finale.parquet à travers le 
fichier pre_process.data

In [4]:
DBO = r"data\test_splits_clean.csv"

In [5]:
dfo = pl.read_csv(DBO)

In [6]:

time_cols = [c for c in dfo.columns if c.endswith("Time")]


pace_cols = [c for c in dfo.columns if c.endswith("pace")]

dfc = dfo.with_columns(
    [parse_hhmmss_seconds(c) for c in time_cols] +
    [parse_mmss_seconds(c) for c in pace_cols]
)

In [7]:
dfa = dfc.filter(
    [pl.col(f"split_{n}_position") == n+1 for n in range(1, 11)]
)

Ici nous avons créée une base de données où les splits sont bien organisé, ce qui donne
un sens à cette catégorie de variable, en plus il y a seulement 2000 individu sur 57000
environ où les splits ne sont pas organisés

In [8]:
dfa

shape: (55_853, 120)
┌──────────┬────────┬───────┬─────────────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ id       ┆ raceId ┆ bib   ┆ firstName   ┆ … ┆ split_10_pa ┆ split_10_s ┆ split_10_d ┆ split_10_p │
│ ---      ┆ ---    ┆ ---   ┆ ---         ┆   ┆ ce          ┆ peed       ┆ istance    ┆ osition    │
│ i64      ┆ i64    ┆ i64   ┆ str         ┆   ┆ ---         ┆ ---        ┆ ---        ┆ ---        │
│          ┆        ┆       ┆             ┆   ┆ i64         ┆ f64        ┆ f64        ┆ i64        │
╞══════════╪════════╪═══════╪═════════════╪═══╪═════════════╪════════════╪════════════╪════════════╡
│ 28057923 ┆ 80626  ┆ 10    ┆ Yemaneberha ┆ … ┆ 164         ┆ 21.89      ┆ 42.195     ┆ 11         │
│          ┆        ┆       ┆ n           ┆   ┆             ┆            ┆            ┆            │
│ 28057924 ┆ 80626  ┆ 19    ┆ Bayelign    ┆ … ┆ 167         ┆ 21.53      ┆ 42.195     ┆ 11         │
│ 28057925 ┆ 80626  ┆ 12    ┆ Sila        ┆ … ┆ 169         ┆ 21.3       ┆ 42.195     ┆ 11         │
│ 28057926 ┆ 80626  ┆ 26    ┆ Mohamed     ┆ … ┆ 174         ┆ 20.74      ┆ 42.195     ┆ 11         │
│ 28057927 ┆ 80626  ┆ 3     ┆ Awet        ┆ … ┆ 175         ┆ 20.52      ┆ 42.195     ┆ 11         │
│          ┆        ┆       ┆ nftalem     ┆   ┆             ┆            ┆            ┆            │
│ …        ┆ …      ┆ …     ┆ …           ┆ … ┆ …           ┆ …          ┆ …          ┆ …          │
│ 29023204 ┆ 80626  ┆ 67221 ┆ Madeleine   ┆ … ┆ 415         ┆ 8.67       ┆ 42.195     ┆ 11         │
│ 29147427 ┆ 80626  ┆ 65648 ┆ Alessia     ┆ … ┆ 451         ┆ 7.97       ┆ 42.195     ┆ 11         │
│ 29204951 ┆ 80626  ┆ 75239 ┆ Camille     ┆ … ┆ 434         ┆ 8.29       ┆ 42.195     ┆ 11         │
│ 29204954 ┆ 80626  ┆ 77728 ┆ Katherine   ┆ … ┆ 507         ┆ 7.1        ┆ 42.195     ┆ 11         │
│ 29263066 ┆ 80626  ┆ 75990 ┆ Emma        ┆ … ┆ 536         ┆ 6.71       ┆ 42.195     ┆ 11         │
└──────────┴────────┴───────┴─────────────┴───┴─────────────┴────────────┴────────────┴────────────┘

In [9]:
dfc

shape: (57_477, 120)
┌──────────┬────────┬───────┬─────────────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ id       ┆ raceId ┆ bib   ┆ firstName   ┆ … ┆ split_10_pa ┆ split_10_s ┆ split_10_d ┆ split_10_p │
│ ---      ┆ ---    ┆ ---   ┆ ---         ┆   ┆ ce          ┆ peed       ┆ istance    ┆ osition    │
│ i64      ┆ i64    ┆ i64   ┆ str         ┆   ┆ ---         ┆ ---        ┆ ---        ┆ ---        │
│          ┆        ┆       ┆             ┆   ┆ i64         ┆ f64        ┆ f64        ┆ i64        │
╞══════════╪════════╪═══════╪═════════════╪═══╪═════════════╪════════════╪════════════╪════════════╡
│ 28057923 ┆ 80626  ┆ 10    ┆ Yemaneberha ┆ … ┆ 164         ┆ 21.89      ┆ 42.195     ┆ 11         │
│          ┆        ┆       ┆ n           ┆   ┆             ┆            ┆            ┆            │
│ 28057924 ┆ 80626  ┆ 19    ┆ Bayelign    ┆ … ┆ 167         ┆ 21.53      ┆ 42.195     ┆ 11         │
│ 28057925 ┆ 80626  ┆ 12    ┆ Sila        ┆ … ┆ 169         ┆ 21.3       ┆ 42.195     ┆ 11         │
│ 28057926 ┆ 80626  ┆ 26    ┆ Mohamed     ┆ … ┆ 174         ┆ 20.74      ┆ 42.195     ┆ 11         │
│ 28057927 ┆ 80626  ┆ 3     ┆ Awet        ┆ … ┆ 175         ┆ 20.52      ┆ 42.195     ┆ 11         │
│          ┆        ┆       ┆ nftalem     ┆   ┆             ┆            ┆            ┆            │
│ …        ┆ …      ┆ …     ┆ …           ┆ … ┆ …           ┆ …          ┆ …          ┆ …          │
│ 29204951 ┆ 80626  ┆ 75239 ┆ Camille     ┆ … ┆ 434         ┆ 8.29       ┆ 42.195     ┆ 11         │
│ 29204952 ┆ 80626  ┆ 69613 ┆ Charles     ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ 29204953 ┆ 80626  ┆ 80434 ┆ Inès        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ 29204954 ┆ 80626  ┆ 77728 ┆ Katherine   ┆ … ┆ 507         ┆ 7.1        ┆ 42.195     ┆ 11         │
│ 29263066 ┆ 80626  ┆ 75990 ┆ Emma        ┆ … ┆ 536         ┆ 6.71       ┆ 42.195     ┆ 11         │
└──────────┴────────┴───────┴─────────────┴───┴─────────────┴────────────┴────────────┴────────────┘

In [10]:
dfo

shape: (57_477, 120)
┌──────────┬────────┬───────┬─────────────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ id       ┆ raceId ┆ bib   ┆ firstName   ┆ … ┆ split_10_pa ┆ split_10_s ┆ split_10_d ┆ split_10_p │
│ ---      ┆ ---    ┆ ---   ┆ ---         ┆   ┆ ce          ┆ peed       ┆ istance    ┆ osition    │
│ i64      ┆ i64    ┆ i64   ┆ str         ┆   ┆ ---         ┆ ---        ┆ ---        ┆ ---        │
│          ┆        ┆       ┆             ┆   ┆ str         ┆ f64        ┆ f64        ┆ i64        │
╞══════════╪════════╪═══════╪═════════════╪═══╪═════════════╪════════════╪════════════╪════════════╡
│ 28057923 ┆ 80626  ┆ 10    ┆ Yemaneberha ┆ … ┆ 2:44        ┆ 21.89      ┆ 42.195     ┆ 11         │
│          ┆        ┆       ┆ n           ┆   ┆             ┆            ┆            ┆            │
│ 28057924 ┆ 80626  ┆ 19    ┆ Bayelign    ┆ … ┆ 2:47        ┆ 21.53      ┆ 42.195     ┆ 11         │
│ 28057925 ┆ 80626  ┆ 12    ┆ Sila        ┆ … ┆ 2:49        ┆ 21.3       ┆ 42.195     ┆ 11         │
│ 28057926 ┆ 80626  ┆ 26    ┆ Mohamed     ┆ … ┆ 2:54        ┆ 20.74      ┆ 42.195     ┆ 11         │
│ 28057927 ┆ 80626  ┆ 3     ┆ Awet        ┆ … ┆ 2:55        ┆ 20.52      ┆ 42.195     ┆ 11         │
│          ┆        ┆       ┆ nftalem     ┆   ┆             ┆            ┆            ┆            │
│ …        ┆ …      ┆ …     ┆ …           ┆ … ┆ …           ┆ …          ┆ …          ┆ …          │
│ 29204951 ┆ 80626  ┆ 75239 ┆ Camille     ┆ … ┆ 7:14        ┆ 8.29       ┆ 42.195     ┆ 11         │
│ 29204952 ┆ 80626  ┆ 69613 ┆ Charles     ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ 29204953 ┆ 80626  ┆ 80434 ┆ Inès        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ 29204954 ┆ 80626  ┆ 77728 ┆ Katherine   ┆ … ┆ 8:27        ┆ 7.1        ┆ 42.195     ┆ 11         │
│ 29263066 ┆ 80626  ┆ 75990 ┆ Emma        ┆ … ┆ 8:56        ┆ 6.71       ┆ 42.195     ┆ 11         │
└──────────┴────────┴───────┴─────────────┴───┴─────────────┴────────────┴────────────┴────────────┘

## 1. Id et Race ID

In [11]:
dfo["bib"].n_unique() == dfo.shape[0]

True

In [12]:
dfo["raceId"].unique()

shape: (1,)
Series: 'raceId' [i64]
[
	80626
]

On voit ici que raceId est unique et que bib peut définir une id étant donné sa 
bijectivité

## 2. Split n

In [30]:
abondonne = [pl.col(f"split_{n}_distance") == 42.195 for n in range(1, 11)]
f"{dfc.filter(pl.any_horizontal(abondonne)).shape[0]} personnes n'ont pas abondonné, soit la totalité"

"57477 personnes n'ont pas abondonné, soit la totalité"

In [14]:
with pl.Config(tbl_rows=100):
    print(dfc["split_2_location"].unique())

shape: (11,)
Series: 'split_2_location' [str]
[
	"FINISH"
	"KM10"
	"KM40"
	"KM21"
	"KM25"
	"KM15"
	"KM30"
	"KM5"
	"KM35"
	null
	"KM20"
]

On voit ici que le split 2 contient beaucoup d'autre splits car pas toute les splits ne
sont enregistré chez les jours

In [15]:
with pl.Config(tbl_cols=150):
    resultat = dfc.filter(
        (pl.col("split_5_distance") != 42.195) &
        (pl.col("split_6_distance").is_null())
        )

    if resultat.shape[0] > 0:
        print(resultat[0])
    else:
        print("Aucune ligne ne correspond à ces critères !")

shape: (1, 120)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ id  ┆ rac ┆ bib ┆ fir ┆ las ┆ tea ┆ pho ┆ vid ┆ reg ┆ sex ┆ cat ┆ nat ┆ rea ┆ off ┆ gen ┆ sex ┆ cat ┆ pac ┆ ave ┆ add ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl │
│ --- ┆ eId ┆ --- ┆ stN ┆ tNa ┆ m   ┆ toL ┆ eoL ┆ ist ┆ --- ┆ ego ┆ ion ┆ lTi ┆ ici ┆ era ┆ Ran ┆ ego ┆ e   ┆ rag ┆ Dis ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ │
│ i64 ┆ --- ┆ i64 ┆ ame ┆ me  ┆ --- ┆ ink ┆ ink ┆ rat ┆ str ┆ ry  ┆ ali ┆ me  ┆ alT ┆ lRa ┆ kin ┆ ryR ┆ --- ┆ eSp ┆ tan ┆ 1_l ┆ 1_r ┆ 1_o ┆ 1_r ┆ 1_r ┆ 1_r ┆ 1_p ┆ 1_s ┆ 1_d ┆ 1_p ┆ 2_l ┆ 2_r ┆ 2_o ┆ 2_r ┆ 2_r ┆ 2_r ┆ 2_p ┆ 2_s ┆ 2_d ┆ 2_p ┆ 3_l ┆ 3_r ┆ 3_o ┆ 3_r ┆ 3_r ┆ 3_r ┆ 3_p ┆ 3_s ┆ 3_d ┆ 3_p ┆ 4_l ┆ 4_r ┆ 4_o ┆ 4_r ┆ 4_r ┆ 4_r ┆ 4_p ┆ 4_s ┆ 4_d ┆ 4_p ┆ 5_l ┆ 5_r ┆ 5_o ┆ 5_r ┆ 5_r ┆ 5_r ┆ 5_p ┆ 5_s ┆ 5_d ┆ 5_p ┆ 6_l ┆ 6_r ┆ 6_o ┆ 6_r ┆ 6_r ┆ 6_r ┆ 6_p ┆ 6_s ┆ 6_d ┆ 6_p ┆ 7_l ┆ 7_r ┆ 7_o ┆ 7_r ┆ 7_r ┆ 7_r ┆ 7_p ┆ 7_s ┆ 7_d ┆ 7_p ┆ 8_l ┆ 8_r ┆ 8_o ┆ 8_r ┆ 8_r ┆ 8_r ┆ 8_p ┆ 8_s ┆ 8_d ┆ 8_p ┆ 9_l ┆ 9_r ┆ 9_o ┆ 9_r ┆ 9_r ┆ 9_r ┆ 9_p ┆ 9_s ┆ 9_d ┆ 9_p ┆ 10_ ┆ 10_ ┆ 10_ ┆ 10_ ┆ 10_ ┆ 10_ ┆ 10_ ┆ 10_ ┆ 10_ ┆ 10_ │
│     ┆ i64 ┆     ┆ --- ┆ --- ┆ str ┆ --- ┆ --- ┆ ion ┆     ┆ --- ┆ ty  ┆ --- ┆ ime ┆ nki ┆ g   ┆ ank ┆ i64 ┆ eed ┆ ce  ┆ oca ┆ eal ┆ ffi ┆ ank ┆ ank ┆ ank ┆ ace ┆ pee ┆ ist ┆ osi ┆ oca ┆ eal ┆ ffi ┆ ank ┆ ank ┆ ank ┆ ace ┆ pee ┆ ist ┆ osi ┆ oca ┆ eal ┆ ffi ┆ ank ┆ ank ┆ ank ┆ ace ┆ pee ┆ ist ┆ osi ┆ oca ┆ eal ┆ ffi ┆ ank ┆ ank ┆ ank ┆ ace ┆ pee ┆ ist ┆ osi ┆ oca ┆ eal ┆ ffi ┆ ank ┆ ank ┆ ank ┆ ace ┆ pee ┆ ist ┆ osi ┆ oca ┆ eal ┆ ffi ┆ ank ┆ ank ┆ ank ┆ ace ┆ pee ┆ ist ┆ osi ┆ oca ┆ eal ┆ ffi ┆ ank ┆ ank ┆ ank ┆ ace ┆ pee ┆ ist ┆ osi ┆ oca ┆ eal ┆ ffi ┆ ank ┆ ank ┆ ank ┆ ace ┆ pee ┆ ist ┆ osi ┆ oca ┆ eal ┆ ffi ┆ ank ┆ ank ┆ ank ┆ ace ┆ pee ┆ ist ┆ osi ┆ loc ┆ rea ┆ off ┆ ran ┆ ran ┆ ran ┆ pac ┆ spe ┆ dis ┆ pos │
│     ┆     ┆     ┆ str ┆ str ┆     ┆ str ┆ str ┆ Cod ┆     ┆ str ┆ --- ┆ i64 ┆ --- ┆ ng  ┆ --- ┆ ing ┆     ┆ --- ┆ --- ┆ tio ┆ Tim ┆ cia ┆ Gen ┆ Sex ┆ Cat ┆ --- ┆ d   ┆ anc ┆ tio ┆ tio ┆ Tim ┆ cia ┆ Gen ┆ Sex ┆ Cat ┆ --- ┆ d   ┆ anc ┆ tio ┆ tio ┆ Tim ┆ cia ┆ Gen ┆ Sex ┆ Cat ┆ --- ┆ d   ┆ anc ┆ tio ┆ tio ┆ Tim ┆ cia ┆ Gen ┆ Sex ┆ Cat ┆ --- ┆ d   ┆ anc ┆ tio ┆ tio ┆ Tim ┆ cia ┆ Gen ┆ Sex ┆ Cat ┆ --- ┆ d   ┆ anc ┆ tio ┆ tio ┆ Tim ┆ cia ┆ Gen ┆ Sex ┆ Cat ┆ --- ┆ d   ┆ anc ┆ tio ┆ tio ┆ Tim ┆ cia ┆ Gen ┆ Sex ┆ Cat ┆ --- ┆ d   ┆ anc ┆ tio ┆ tio ┆ Tim ┆ cia ┆ Gen ┆ Sex ┆ Cat ┆ --- ┆ d   ┆ anc ┆ tio ┆ tio ┆ Tim ┆ cia ┆ Gen ┆ Sex ┆ Cat ┆ --- ┆ d   ┆ anc ┆ tio ┆ ati ┆ lTi ┆ ici ┆ kGe ┆ kSe ┆ kCa ┆ e   ┆ ed  ┆ tan ┆ iti │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆ str ┆     ┆ i64 ┆ --- ┆ i64 ┆ --- ┆     ┆ f64 ┆ i64 ┆ n   ┆ e   ┆ lTi ┆ era ┆ --- ┆ ego ┆ i64 ┆ --- ┆ e   ┆ n   ┆ n   ┆ e   ┆ lTi ┆ era ┆ --- ┆ ego ┆ i64 ┆ --- ┆ e   ┆ n   ┆ n   ┆ e   ┆ lTi ┆ era ┆ --- ┆ ego ┆ i64 ┆ --- ┆ e   ┆ n   ┆ n   ┆ e   ┆ lTi ┆ era ┆ --- ┆ ego ┆ i64 ┆ --- ┆ e   ┆ n   ┆ n   ┆ e   ┆ lTi ┆ era ┆ --- ┆ ego ┆ i64 ┆ --- ┆ e   ┆ n   ┆ n   ┆ e   ┆ lTi ┆ era ┆ --- ┆ ego ┆ i64 ┆ --- ┆ e   ┆ n   ┆ n   ┆ e   ┆ lTi ┆ era ┆ --- ┆ ego ┆ i64 ┆ --- ┆ e   ┆ n   ┆ n   ┆ e   ┆ lTi ┆ era ┆ --- ┆ ego ┆ i64 ┆ --- ┆ e   ┆ n   ┆ n   ┆ e   ┆ lTi ┆ era ┆ --- ┆ ego ┆ i64 ┆ --- ┆ e   ┆ n   ┆ on  ┆ me  ┆ alT ┆ ner ┆ x   ┆ teg ┆ --- ┆ --- ┆ ce  ┆ on  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆ i64 ┆     ┆     ┆     ┆ --- ┆ --- ┆ me  ┆ l   ┆ i64 ┆ ry  ┆     ┆ f64 ┆ --- ┆ --- ┆ --- ┆ --- ┆ me  ┆ l   ┆ i64 ┆ ry  ┆     ┆ f64 ┆ --- ┆ --- ┆ --- ┆ --- ┆ me  ┆ l   ┆ i64 ┆ ry  ┆     ┆ f64 ┆ --- ┆ --- ┆ --- ┆ --- ┆ me  ┆ l   ┆ i64 ┆ ry  ┆     ┆ f64 ┆ --- ┆ --- ┆ --- ┆ --- ┆ me  ┆ l   ┆ i64 ┆ ry  ┆     ┆ f64 ┆ --- ┆ --- ┆ --- ┆ --- ┆ me  ┆ l   ┆ i64 ┆ ry  ┆     ┆ f64 ┆ --- ┆ --- ┆ --- ┆ --- ┆ me  ┆ l   ┆ i64 ┆ ry  ┆     ┆ f64 ┆ --- ┆ --- ┆ --- ┆ --- ┆ me  ┆ l   ┆ i64 ┆ ry  ┆     ┆ f64 ┆ --- ┆ --- ┆ --- ┆ --- ┆ me  ┆ l   ┆ i64 ┆ ry  ┆     ┆ f64 ┆ --- ┆ --- ┆ --- ┆ --- ┆ ime ┆ al  ┆ --- ┆ ory ┆ i64 ┆ f64 ┆ --- ┆ --- │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ i64 ┆ --- ┆ --- ┆     ┆ --- ┆     ┆     ┆ f64 ┆ i64 ┆ str ┆ i64 ┆ --- ┆ --- ┆     ┆ --- ┆     ┆     ┆ f64 ┆ i64 ┆ str ┆ i64 ┆ --- ┆ --- ┆     ┆ --- ┆     ┆     ┆ f64 ┆ i64 ┆ str ┆ i64 ┆ --- ┆ --- ┆     ┆ --- ┆     ┆     ┆ f64 ┆ i64 ┆ str ┆ i64 ┆ --- ┆ --- ┆     ┆ --- ┆     ┆     ┆ f64 ┆ i64 ┆ str ┆ i64 ┆ --- ┆ --- ┆     ┆ --- ┆     ┆     ┆ f64 ┆ i64 ┆ str ┆ i64 ┆ --- ┆ --- ┆     ┆ --- ┆     ┆     ┆ f64 ┆ i64 ┆ str ┆ i64 ┆ --- ┆ --- ┆     ┆ --- ┆     ┆     ┆ f64 ┆ i64 ┆ str ┆ i64 ┆ --- ┆ --- ┆     ┆ --- ┆     ┆     ┆ f64 ┆ i64 ┆ str ┆ i64 ┆ --- ┆ --- ┆ i64 ┆ --- ┆     ┆     ┆ f64 ┆ i64 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆ i64 ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 282 ┆ 806 ┆ 220 ┆ Chr ┆ LAN ┆     ┆ htt ┆ nul ┆ 69d ┆ M   ┆ M3H ┆ FR  ┆ 224 ┆ 280 ┆ 567 ┆ 389 ┆ 361 ┆ 532 ┆ 6.7 ┆ 0   ┆ KM5 ┆ 140 ┆ 701 ┆ 162 ┆ 141 ┆ 117 ┆ 281 ┆ 12. ┆ 5.0 ┆ 2   ┆ KM1 ┆ 472 ┆ 472 ┆ 291 ┆ 235 ┆ 209 ┆ 945 ┆ 3.8 ┆ 10. ┆ 3   ┆ KM3 ┆ 114 ┆ 114 ┆ 456 ┆ 337 ┆ 306 ┆ 573 ┆ 6.2 ┆ 30. ┆ 8   ┆ FIN ┆ 0   ┆ 0   ┆ 445 ┆ 329 ┆ 297 ┆ nul ┆ nul ┆ 42. ┆ 11  ┆ KM4 ┆ 768 ┆ 768 ┆ 528 ┆ 371 ┆ 342 ┆ 768 ┆ 4.6 ┆ 40. ┆ 10  ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul │
│ 719 ┆ 26  ┆ 14  ┆ ist ┆ DRY ┆     ┆ ps: ┆ l   ┆ 50e ┆     ┆     ┆     ┆ 32  ┆ 46  ┆ 98  ┆ 27  ┆ 4   ┆     ┆ 7   ┆     ┆     ┆ 3   ┆ 7   ┆ 99  ┆ 84  ┆ 9   ┆     ┆ 83  ┆     ┆     ┆ 0   ┆ 7   ┆ 6   ┆ 25  ┆ 40  ┆ 5   ┆     ┆ 1   ┆ 0   ┆     ┆ 0   ┆ 55  ┆ 55  ┆ 72  ┆ 53  ┆ 0   ┆     ┆ 9   ┆ 0   ┆     ┆ ISH ┆     ┆     ┆ 26  ┆ 32  ┆ 2   ┆ l   ┆ l   ┆ 195 ┆     ┆ 0   ┆ 0   ┆ 0   ┆ 78  ┆ 78  ┆ 9   ┆     ┆ 9   ┆ 0   ┆     ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   │
│ 06  ┆     ┆     ┆ oph ┆     ┆     ┆ //m ┆     ┆ fef ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ er  ┆     ┆     ┆ ara ┆     ┆ e48 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ tho ┆     ┆ d62 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ nph ┆     ┆ 946 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ oto ┆     ┆ 6f4 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ s.l ┆     ┆ 9cb ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ ive ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ /Ev ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

Ici on voit par exemple que plusieur splits manquent, et en plus les 2 derniers split
ne sont pas à la bonne place

In [16]:
dfc.select(pl.all_horizontal(
    [pl.col(f"split_{n}_distance").is_not_null() for n in range(1, 11)]
).sum()).item()

55858

In [17]:
dfa.shape[0]

55853

On voit ici que seulement 5 individu ont tout leurs split remplis mais ne sont pas bien
trié, ce qui est peu, donc on se permet aussi de filtrer ceux pour qui les splits ne sont 
pas bien organisé

In [18]:
mapping = {
    1 : ("KM5", 5.0),
    2 : ("KM10", 10.0),
    3 : ("KM15", 15.0),
    4 : ("KM20", 20.0),
    5 : ("KM21", 21.1),
    6 : ("KM25", 25.0),
    7 : ("KM30", 30.0),
    8 : ("KM35", 35.0),
    9 : ("KM40", 40.0),
    10 : ("FINISH", 42.195)
}

cond = (
    [pl.col(f"split_{n}_location") == mapping[n][0] for n in range(1, 11)] +
    [pl.col(f"split_{n}_distance") == mapping[n][1] for n in range(1, 11)] +
    [pl.col(f"split_{n}_position") == n+1 for n in range(1, 11)]
)

In [19]:
dfc.filter(cond).shape[0]

55853

Ici on voit que location, distance, position donne les mêmes information donc il faut en
garder un et enlever les autres, on garde distance.

## 3.1 realTime vs OfficialTime

L'official time est le temps écoulé après que le tout premier coureur soit partie, 
et real time est le temps écoulé du coureur, donc c'est le vrai temps personnelle.
Official time est inutile à première vu mais il permet de modéliser le "retard", c'est à
l'heure à laquelle le joueur a commencé.

In [20]:
df_ro = dfc.filter(
    pl.col("officialTime").is_not_null() &
    pl.col("realTime").is_not_null()
).select(["officialTime", "realTime"])

In [21]:
df_ro = df_ro.with_columns(
    (pl.col("officialTime") - pl.col("realTime")).alias("diff")
)
with pl.Config(tbl_rows=20):
    print(df_ro.sort("diff", descending=True).head(20))

shape: (20, 3)
┌──────────────┬──────────┬───────┐
│ officialTime ┆ realTime ┆ diff  │
│ ---          ┆ ---      ┆ ---   │
│ i64          ┆ i64      ┆ i64   │
╞══════════════╪══════════╪═══════╡
│ 32694        ┆ 18326    ┆ 14368 │
│ 33894        ┆ 19551    ┆ 14343 │
│ 34558        ┆ 20215    ┆ 14343 │
│ 31779        ┆ 17438    ┆ 14341 │
│ 32342        ┆ 18002    ┆ 14340 │
│ 33426        ┆ 19087    ┆ 14339 │
│ 33640        ┆ 19301    ┆ 14339 │
│ 30589        ┆ 16252    ┆ 14337 │
│ 31304        ┆ 16967    ┆ 14337 │
│ 32294        ┆ 17957    ┆ 14337 │
│ 32589        ┆ 18252    ┆ 14337 │
│ 32839        ┆ 18502    ┆ 14337 │
│ 34582        ┆ 20245    ┆ 14337 │
│ 30661        ┆ 16325    ┆ 14336 │
│ 31064        ┆ 16728    ┆ 14336 │
│ 31304        ┆ 16968    ┆ 14336 │
│ 32524        ┆ 18188    ┆ 14336 │
│ 35320        ┆ 20984    ┆ 14336 │
│ 35395        ┆ 21059    ┆ 14336 │
│ 35645        ┆ 21309    ┆ 14336 │
└──────────────┴──────────┴───────┘

In [31]:
df_ro["diff"].mean()

7761.114236999148

## 3.2 realTime vs OfficialTime n split

In [23]:
column_ros = [col for pair in zip(
    [f"split_{n}_realTime" for n in range(1, 11)],
    [f"split_{n}_officialTime" for n in range(1, 11)]
) for col in pair]

df_ros = dfa.select(column_ros)

df_ros = df_ros.with_columns(
    [(
        pl.col(f"split_{n}_officialTime") - pl.col(f"split_{n}_realTime")
        ).alias(f"split_{n}_diff") for n in range(1, 11)]
)

In [24]:
df_ros

shape: (55_853, 30)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ split_1_r ┆ split_1_o ┆ split_2_r ┆ split_2_o ┆ … ┆ split_7_d ┆ split_8_d ┆ split_9_d ┆ split_10 │
│ ealTime   ┆ fficialTi ┆ ealTime   ┆ fficialTi ┆   ┆ iff       ┆ iff       ┆ iff       ┆ _diff    │
│ ---       ┆ me        ┆ ---       ┆ me        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ i64       ┆ ---       ┆ i64       ┆ ---       ┆   ┆ i64       ┆ i64       ┆ i64       ┆ i64      │
│           ┆ i64       ┆           ┆ i64       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 895       ┆ 895       ┆ 897       ┆ 897       ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ 897       ┆ 897       ┆ 897       ┆ 897       ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ 895       ┆ 895       ┆ 897       ┆ 897       ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ 895       ┆ 895       ┆ 897       ┆ 897       ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ 896       ┆ 896       ┆ 898       ┆ 898       ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 13891     ┆ 13891     ┆ 2090      ┆ 2090      ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ 14385     ┆ 14385     ┆ 2091      ┆ 2091      ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ 15668     ┆ 15668     ┆ 2364      ┆ 2364      ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ 14996     ┆ 14996     ┆ 2464      ┆ 2464      ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ 15359     ┆ 15359     ┆ 2312      ┆ 2312      ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [25]:
df_max = df_ros.select(
    pl.col("^split_.*_diff$").mean()
)

df_max

shape: (1, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ split_1_d ┆ split_2_d ┆ split_3_d ┆ split_4_d ┆ … ┆ split_7_d ┆ split_8_d ┆ split_9_d ┆ split_10 │
│ iff       ┆ iff       ┆ iff       ┆ iff       ┆   ┆ iff       ┆ iff       ┆ iff       ┆ _diff    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 7717.3733 ┆ 4.005729  ┆ 4.119349  ┆ -0.014484 ┆ … ┆ 0.008182  ┆ -0.011351 ┆ -0.002363 ┆ -0.01484 │
│ 01        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

On remarque que diff sur split1 est assez proche du retard définie précédemment, c'est
enfaite car il garde la même logique, temps écoulé entre le passe en split1 et le départ
du 1er coureur. alors que les autres sont assez petit donc officialtime ne sert pratiquement 
à rien

In [26]:
with pl.Config(tbl_cols=150):
    print(dfa[df_ros.select(pl.col("split_2_diff").arg_max()).item()])

shape: (1, 120)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ id  ┆ rac ┆ bib ┆ fir ┆ las ┆ tea ┆ pho ┆ vid ┆ reg ┆ sex ┆ cat ┆ nat ┆ rea ┆ off ┆ gen ┆ sex ┆ cat ┆ pac ┆ ave ┆ add ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl ┆ spl │
│ --- ┆ eId ┆ --- ┆ stN ┆ tNa ┆ m   ┆ toL ┆ eoL ┆ ist ┆ --- ┆ ego ┆ ion ┆ lTi ┆ ici ┆ era ┆ Ran ┆ ego ┆ e   ┆ rag ┆ Dis ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ ┆ it_ │
│ i64 ┆ --- ┆ i64 ┆ ame ┆ me  ┆ --- ┆ ink ┆ ink ┆ rat ┆ str ┆ ry  ┆ ali ┆ me  ┆ alT ┆ lRa ┆ kin ┆ ryR ┆ --- ┆ eSp ┆ tan ┆ 1_l ┆ 1_r ┆ 1_o ┆ 1_r ┆ 1_r ┆ 1_r ┆ 1_p ┆ 1_s ┆ 1_d ┆ 1_p ┆ 2_l ┆ 2_r ┆ 2_o ┆ 2_r ┆ 2_r ┆ 2_r ┆ 2_p ┆ 2_s ┆ 2_d ┆ 2_p ┆ 3_l ┆ 3_r ┆ 3_o ┆ 3_r ┆ 3_r ┆ 3_r ┆ 3_p ┆ 3_s ┆ 3_d ┆ 3_p ┆ 4_l ┆ 4_r ┆ 4_o ┆ 4_r ┆ 4_r ┆ 4_r ┆ 4_p ┆ 4_s ┆ 4_d ┆ 4_p ┆ 5_l ┆ 5_r ┆ 5_o ┆ 5_r ┆ 5_r ┆ 5_r ┆ 5_p ┆ 5_s ┆ 5_d ┆ 5_p ┆ 6_l ┆ 6_r ┆ 6_o ┆ 6_r ┆ 6_r ┆ 6_r ┆ 6_p ┆ 6_s ┆ 6_d ┆ 6_p ┆ 7_l ┆ 7_r ┆ 7_o ┆ 7_r ┆ 7_r ┆ 7_r ┆ 7_p ┆ 7_s ┆ 7_d ┆ 7_p ┆ 8_l ┆ 8_r ┆ 8_o ┆ 8_r ┆ 8_r ┆ 8_r ┆ 8_p ┆ 8_s ┆ 8_d ┆ 8_p ┆ 9_l ┆ 9_r ┆ 9_o ┆ 9_r ┆ 9_r ┆ 9_r ┆ 9_p ┆ 9_s ┆ 9_d ┆ 9_p ┆ 10_ ┆ 10_ ┆ 10_ ┆ 10_ ┆ 10_ ┆ 10_ ┆ 10_ ┆ 10_ ┆ 10_ ┆ 10_ │
│     ┆ i64 ┆     ┆ --- ┆ --- ┆ str ┆ --- ┆ --- ┆ ion ┆     ┆ --- ┆ ty  ┆ --- ┆ ime ┆ nki ┆ g   ┆ ank ┆ i64 ┆ eed ┆ ce  ┆ oca ┆ eal ┆ ffi ┆ ank ┆ ank ┆ ank ┆ ace ┆ pee ┆ ist ┆ osi ┆ oca ┆ eal ┆ ffi ┆ ank ┆ ank ┆ ank ┆ ace ┆ pee ┆ ist ┆ osi ┆ oca ┆ eal ┆ ffi ┆ ank ┆ ank ┆ ank ┆ ace ┆ pee ┆ ist ┆ osi ┆ oca ┆ eal ┆ ffi ┆ ank ┆ ank ┆ ank ┆ ace ┆ pee ┆ ist ┆ osi ┆ oca ┆ eal ┆ ffi ┆ ank ┆ ank ┆ ank ┆ ace ┆ pee ┆ ist ┆ osi ┆ oca ┆ eal ┆ ffi ┆ ank ┆ ank ┆ ank ┆ ace ┆ pee ┆ ist ┆ osi ┆ oca ┆ eal ┆ ffi ┆ ank ┆ ank ┆ ank ┆ ace ┆ pee ┆ ist ┆ osi ┆ oca ┆ eal ┆ ffi ┆ ank ┆ ank ┆ ank ┆ ace ┆ pee ┆ ist ┆ osi ┆ oca ┆ eal ┆ ffi ┆ ank ┆ ank ┆ ank ┆ ace ┆ pee ┆ ist ┆ osi ┆ loc ┆ rea ┆ off ┆ ran ┆ ran ┆ ran ┆ pac ┆ spe ┆ dis ┆ pos │
│     ┆     ┆     ┆ str ┆ str ┆     ┆ str ┆ str ┆ Cod ┆     ┆ str ┆ --- ┆ i64 ┆ --- ┆ ng  ┆ --- ┆ ing ┆     ┆ --- ┆ --- ┆ tio ┆ Tim ┆ cia ┆ Gen ┆ Sex ┆ Cat ┆ --- ┆ d   ┆ anc ┆ tio ┆ tio ┆ Tim ┆ cia ┆ Gen ┆ Sex ┆ Cat ┆ --- ┆ d   ┆ anc ┆ tio ┆ tio ┆ Tim ┆ cia ┆ Gen ┆ Sex ┆ Cat ┆ --- ┆ d   ┆ anc ┆ tio ┆ tio ┆ Tim ┆ cia ┆ Gen ┆ Sex ┆ Cat ┆ --- ┆ d   ┆ anc ┆ tio ┆ tio ┆ Tim ┆ cia ┆ Gen ┆ Sex ┆ Cat ┆ --- ┆ d   ┆ anc ┆ tio ┆ tio ┆ Tim ┆ cia ┆ Gen ┆ Sex ┆ Cat ┆ --- ┆ d   ┆ anc ┆ tio ┆ tio ┆ Tim ┆ cia ┆ Gen ┆ Sex ┆ Cat ┆ --- ┆ d   ┆ anc ┆ tio ┆ tio ┆ Tim ┆ cia ┆ Gen ┆ Sex ┆ Cat ┆ --- ┆ d   ┆ anc ┆ tio ┆ tio ┆ Tim ┆ cia ┆ Gen ┆ Sex ┆ Cat ┆ --- ┆ d   ┆ anc ┆ tio ┆ ati ┆ lTi ┆ ici ┆ kGe ┆ kSe ┆ kCa ┆ e   ┆ ed  ┆ tan ┆ iti │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆ str ┆     ┆ i64 ┆ --- ┆ i64 ┆ --- ┆     ┆ f64 ┆ i64 ┆ n   ┆ e   ┆ lTi ┆ era ┆ --- ┆ ego ┆ i64 ┆ --- ┆ e   ┆ n   ┆ n   ┆ e   ┆ lTi ┆ era ┆ --- ┆ ego ┆ i64 ┆ --- ┆ e   ┆ n   ┆ n   ┆ e   ┆ lTi ┆ era ┆ --- ┆ ego ┆ i64 ┆ --- ┆ e   ┆ n   ┆ n   ┆ e   ┆ lTi ┆ era ┆ --- ┆ ego ┆ i64 ┆ --- ┆ e   ┆ n   ┆ n   ┆ e   ┆ lTi ┆ era ┆ --- ┆ ego ┆ i64 ┆ --- ┆ e   ┆ n   ┆ n   ┆ e   ┆ lTi ┆ era ┆ --- ┆ ego ┆ i64 ┆ --- ┆ e   ┆ n   ┆ n   ┆ e   ┆ lTi ┆ era ┆ --- ┆ ego ┆ i64 ┆ --- ┆ e   ┆ n   ┆ n   ┆ e   ┆ lTi ┆ era ┆ --- ┆ ego ┆ i64 ┆ --- ┆ e   ┆ n   ┆ n   ┆ e   ┆ lTi ┆ era ┆ --- ┆ ego ┆ i64 ┆ --- ┆ e   ┆ n   ┆ on  ┆ me  ┆ alT ┆ ner ┆ x   ┆ teg ┆ --- ┆ --- ┆ ce  ┆ on  │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆ i64 ┆     ┆     ┆     ┆ --- ┆ --- ┆ me  ┆ l   ┆ i64 ┆ ry  ┆     ┆ f64 ┆ --- ┆ --- ┆ --- ┆ --- ┆ me  ┆ l   ┆ i64 ┆ ry  ┆     ┆ f64 ┆ --- ┆ --- ┆ --- ┆ --- ┆ me  ┆ l   ┆ i64 ┆ ry  ┆     ┆ f64 ┆ --- ┆ --- ┆ --- ┆ --- ┆ me  ┆ l   ┆ i64 ┆ ry  ┆     ┆ f64 ┆ --- ┆ --- ┆ --- ┆ --- ┆ me  ┆ l   ┆ i64 ┆ ry  ┆     ┆ f64 ┆ --- ┆ --- ┆ --- ┆ --- ┆ me  ┆ l   ┆ i64 ┆ ry  ┆     ┆ f64 ┆ --- ┆ --- ┆ --- ┆ --- ┆ me  ┆ l   ┆ i64 ┆ ry  ┆     ┆ f64 ┆ --- ┆ --- ┆ --- ┆ --- ┆ me  ┆ l   ┆ i64 ┆ ry  ┆     ┆ f64 ┆ --- ┆ --- ┆ --- ┆ --- ┆ me  ┆ l   ┆ i64 ┆ ry  ┆     ┆ f64 ┆ --- ┆ --- ┆ --- ┆ --- ┆ ime ┆ al  ┆ --- ┆ ory ┆ i64 ┆ f64 ┆ --- ┆ --- │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ i64 ┆ --- ┆ --- ┆     ┆ --- ┆     ┆     ┆ f64 ┆ i64 ┆ str ┆ i64 ┆ --- ┆ --- ┆     ┆ --- ┆     ┆     ┆ f64 ┆ i64 ┆ str ┆ i64 ┆ --- ┆ --- ┆     ┆ --- ┆     ┆     ┆ f64 ┆ i64 ┆ str ┆ i64 ┆ --- ┆ --- ┆     ┆ --- ┆     ┆     ┆ f64 ┆ i64 ┆ str ┆ i64 ┆ --- ┆ --- ┆     ┆ --- ┆     ┆     ┆ f64 ┆ i64 ┆ str ┆ i64 ┆ --- ┆ --- ┆     ┆ --- ┆     ┆     ┆ f64 ┆ i64 ┆ str ┆ i64 ┆ --- ┆ --- ┆     ┆ --- ┆     ┆     ┆ f64 ┆ i64 ┆ str ┆ i64 ┆ --- ┆ --- ┆     ┆ --- ┆     ┆     ┆ f64 ┆ i64 ┆ str ┆ i64 ┆ --- ┆ --- ┆     ┆ --- ┆     ┆     ┆ f64 ┆ i64 ┆ str ┆ i64 ┆ --- ┆ --- ┆ i64 ┆ --- ┆     ┆     ┆ f64 ┆ i64 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆ i64 ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 292 ┆ 806 ┆ 690 ┆ Fré ┆ POE ┆     ┆ htt ┆ nul ┆ 680 ┆ M   ┆ M5H ┆ FR  ┆ 215 ┆ 348 ┆ 562 ┆ 386 ┆ 137 ┆ 510 ┆ 7.0 ┆ 0   ┆ KM5 ┆ 523 ┆ 523 ┆ 105 ┆ 952 ┆ 187 ┆ 104 ┆ 3.4 ┆ 5.0 ┆ 2   ┆ KM1 ┆ 0   ┆ 123 ┆ 537 ┆ 377 ┆ 132 ┆ nul ┆ nul ┆ 10. ┆ 3   ┆ KM1 ┆ 228 ┆ 228 ┆ 544 ┆ 380 ┆ 134 ┆ 457 ┆ 7.8 ┆ 15. ┆ 4   ┆ KM2 ┆ 250 ┆ 250 ┆ 554 ┆ 384 ┆ 136 ┆ 502 ┆ 7.1 ┆ 20. ┆ 5   ┆ KM2 ┆ 640 ┆ 641 ┆ 555 ┆ 384 ┆ 137 ┆ 582 ┆ 6.1 ┆ 21. ┆ 6   ┆ KM2 ┆ 211 ┆ 211 ┆ 559 ┆ 386 ┆ 138 ┆ 541 ┆ 6.6 ┆ 25. ┆ 7   ┆ KM3 ┆ 278 ┆ 278 ┆ 560 ┆ 386 ┆ 138 ┆ 557 ┆ 6.4 ┆ 30. ┆ 8   ┆ KM3 ┆ 290 ┆ 290 ┆ 561 ┆ 386 ┆ 138 ┆ 582 ┆ 6.1 ┆ 35. ┆ 9   ┆ KM4 ┆ 291 ┆ 291 ┆ 563 ┆ 387 ┆ 138 ┆ 584 ┆ 6.1 ┆ 40. ┆ 10  ┆ FIN ┆ 109 ┆ 109 ┆ 566 ┆ 389 ┆ 140 ┆ 499 ┆ 7.2 ┆ 42. ┆ 11  │
│ 039 ┆ 26  ┆ 71  ┆ dér ┆ TTO ┆     ┆ ps: ┆ l   ┆ 7a7 ┆     ┆     ┆     ┆ 11  ┆ 69  ┆ 22  ┆ 62  ┆ 9   ┆     ┆ 6   ┆     ┆     ┆ 7   ┆ 7   ┆ 53  ┆ 1   ┆     ┆ 7   ┆ 4   ┆     ┆     ┆ 0   ┆     ┆ 77  ┆ 62  ┆ 49  ┆ 8   ┆ l   ┆ l   ┆ 0   ┆     ┆ 5   ┆ 7   ┆ 7   ┆ 38  ┆ 54  ┆ 4   ┆     ┆ 7   ┆ 0   ┆     ┆ 0   ┆ 9   ┆ 8   ┆ 59  ┆ 47  ┆ 7   ┆     ┆ 7   ┆ 0   ┆     ┆ 1   ┆     ┆     ┆ 99  ┆ 89  ┆ 2   ┆     ┆ 9   ┆ 1   ┆     ┆ 5   ┆ 1   ┆ 1   ┆ 89  ┆ 40  ┆ 7   ┆     ┆ 5   ┆ 0   ┆     ┆ 0   ┆ 6   ┆ 6   ┆ 05  ┆ 03  ┆ 8   ┆     ┆ 6   ┆ 0   ┆     ┆ 5   ┆ 8   ┆ 8   ┆ 65  ┆ 50  ┆ 9   ┆     ┆ 9   ┆ 0   ┆     ┆ 0   ┆ 8   ┆ 8   ┆ 64  ┆ 54  ┆ 5   ┆     ┆ 7   ┆ 0   ┆     ┆ ISH ┆ 6   ┆ 6   ┆ 97  ┆ 43  ┆ 0   ┆     ┆ 1   ┆ 195 ┆     │
│ 21  ┆     ┆     ┆ ic  ┆ Z   ┆     ┆ //m ┆     ┆ 343 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ ara ┆     ┆ e1e ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ tho ┆     ┆ 3b2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ nph ┆     ┆ e38 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ oto ┆     ┆ 20e ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ s.l ┆     ┆ a06 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ ive ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ /Ev ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

On remarque deplus ici que lorsqu'on a de grands écart sur la diff Time sur split,
c'est probablement une erreur machine car realTime est à 0 est speed est sur null.
On préfère supprimer ces lignes.