In [2]:
import polars as pl

In [3]:
df = pl.read_parquet("data/test_parquet.parquet")
df.head()

shape: (5, 113)
┌─────┬──────────────┬──────────┬─────┬───┬──────────────┬─────────────┬─────────────┬─────────────┐
│ bib ┆ firstName    ┆ lastName ┆ sex ┆ … ┆ split_10_pac ┆ split_10_sp ┆ split_10_di ┆ split_10_po │
│ --- ┆ ---          ┆ ---      ┆ --- ┆   ┆ e            ┆ eed         ┆ stance      ┆ sition      │
│ i64 ┆ str          ┆ str      ┆ str ┆   ┆ ---          ┆ ---         ┆ ---         ┆ ---         │
│     ┆              ┆          ┆     ┆   ┆ duration[ns] ┆ f64         ┆ f64         ┆ i64         │
╞═════╪══════════════╪══════════╪═════╪═══╪══════════════╪═════════════╪═════════════╪═════════════╡
│ 10  ┆ Yemaneberhan ┆ CRIPPA   ┆ M   ┆ … ┆ 2m 44s       ┆ 21.89       ┆ 42.195      ┆ 11          │
│ 19  ┆ Bayelign     ┆ TESHAGER ┆ M   ┆ … ┆ 2m 47s       ┆ 21.53       ┆ 42.195      ┆ 11          │
│ 12  ┆ Sila         ┆ KIPTOO   ┆ M   ┆ … ┆ 2m 49s       ┆ 21.3        ┆ 42.195      ┆ 11          │
│ 26  ┆ Mohamed      ┆ ISMAIL   ┆ M   ┆ … ┆ 2m 54s       ┆ 20.74       ┆ 42.195      ┆ 11          │
│ 3   ┆ Awet nftalem ┆ KIBRAB   ┆ M   ┆ … ┆ 2m 55s       ┆ 20.52       ┆ 42.195      ┆ 11          │
└─────┴──────────────┴──────────┴─────┴───┴──────────────┴─────────────┴─────────────┴─────────────┘

In [4]:
df = pl.read_csv("data/test_splits_clean_v2.csv")
df.head()

shape: (5, 113)
┌─────┬──────────────┬──────────┬─────┬───┬──────────────┬─────────────┬─────────────┬─────────────┐
│ bib ┆ firstName    ┆ lastName ┆ sex ┆ … ┆ split_10_pac ┆ split_10_sp ┆ split_10_di ┆ split_10_po │
│ --- ┆ ---          ┆ ---      ┆ --- ┆   ┆ e            ┆ eed         ┆ stance      ┆ sition      │
│ i64 ┆ str          ┆ str      ┆ str ┆   ┆ ---          ┆ ---         ┆ ---         ┆ ---         │
│     ┆              ┆          ┆     ┆   ┆ i64          ┆ f64         ┆ f64         ┆ i64         │
╞═════╪══════════════╪══════════╪═════╪═══╪══════════════╪═════════════╪═════════════╪═════════════╡
│ 10  ┆ Yemaneberhan ┆ CRIPPA   ┆ M   ┆ … ┆ 164          ┆ 21.89       ┆ 42.195      ┆ 11          │
│ 19  ┆ Bayelign     ┆ TESHAGER ┆ M   ┆ … ┆ 167          ┆ 21.53       ┆ 42.195      ┆ 11          │
│ 12  ┆ Sila         ┆ KIPTOO   ┆ M   ┆ … ┆ 169          ┆ 21.3        ┆ 42.195      ┆ 11          │
│ 26  ┆ Mohamed      ┆ ISMAIL   ┆ M   ┆ … ┆ 174          ┆ 20.74       ┆ 42.195      ┆ 11          │
│ 3   ┆ Awet nftalem ┆ KIBRAB   ┆ M   ┆ … ┆ 175          ┆ 20.52       ┆ 42.195      ┆ 11          │
└─────┴──────────────┴──────────┴─────┴───┴──────────────┴─────────────┴─────────────┴─────────────┘